name: Release Software

on:
  workflow_run:
    workflows: ["Test Software"]
    types:
      - completed

jobs:
  release-github:
    name: Create GitHub Release
    if: ${{ github.event.workflow_run.conclusion == 'success' && (startsWith(github.event.workflow_run.head_branch, 'v') || startsWith(github.event.workflow_run.head_sha, 'refs/tags/v')) }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install build tools
      run: python -m pip install build --user
    - name: Build package
      run: python -m build
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
        generate_release_notes: true
        tag_name: ${{ github.event.workflow_run.head_branch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
